export enum OperationType {
  transAlExteriorConCambioD = 7,
  pagoHaberes = 8,
  pagoDeServicios = 9,
  pagoDeServiciosTelefonía = 10,
  consultarCuentas = 12,
  transferenciasCuentasPropias = 13,
  transferenciasCuentasTerceros = 14,
  transferenciasCuentasAutorizadas = 15,
  pagoProveedores = 16,
  formularioSolicitud = 17,
  boletaGarantia = 18,
  identificacionDeAbonos = 19,
  pagoMultiple = 20,
  pagoCreditoEmpresarial = 21,
  pagoFavorito = 23,
  pagoProveedoresAch = 24,
  pagoProveedoresEfe = 25,
  pagoProveedoresChequeGerencia = 26,
  pagoProveedoresOtrosBancosCheque = 27,
  pagoImpuestoGerencia = 28,
  ordenesDeDebitoAOtrosBancos = 29,
  formularioModificacion = 30
}
